### ISSUE TITLE
𓍑 is a biliteral not a uniliteral

### ISSUE THREAD

**Issue by NohaelKa** [NohaelKa/NileLangu_MiddleEgyLessons#4]
Reference is Alan Gardiners introduction to middle egyptian page 30. It shall be removed

**Comment by kaiw1011** [comment]
𓍑 will be replaced with 𓆓 in my edits whenever applicable, I will send another message to let you know when that is done.

**Comment by kaiw1011** [comment]
Please add sound for 𓆓, which replaces fire-drill.

**Comment by NohaelKa** [comment]
𓆓 audio is already there as "DJ"

**Comment by NohaelKa** [comment]
Fixed in v3.6
