### ISSUE TITLE
𓆼 is a biliteral, not a uniliteral

### ISSUE THREAD

**Issue by NohaelKa** [NohaelKa/NileLangu_MiddleEgyLessons#5]
to remove from uniliteral lesson

**Comment by NohaelKa** [comment]
𓆼 removed from Repo. To close the issue once the new app version is released

**Comment by kaiw1011** [comment]
𓆼 is supposed to be 𓐍, I will send another message once this is fixed

**Comment by kaiw1011** [comment]
Please add sound for 𓐍 uniliteral.

**Comment by NohaelKa** [comment]
Added  𓐍 sound in the audio files and removed 𓆼

**Comment by NohaelKa** [comment]
Fixed in v3.6
